name: PR 시 CI 테스트 자동화

on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-2
  ECR_URL: public.ecr.aws/j6g5s0j0/cicd-test:{{ github.sha}}

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - run: touch ./src/main/resources/security.properties
      - run: echo "${{ secrets.SECURITY_PROP }}" > ./src/main/resources/security.properties

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle 종속성 캐시
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 명령 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle로 프로젝트 Build
        run: ./gradlew build

      - name: Container build
        run: docker build -t  . {{ env.ECR_URL }}
        
      - name: Container Push
        run : docker push {{ env.ECR_URL }}
  CD:
    name: Deploy
    runs-on: ubuntu-latest
    run: 
